export type Resource = {
  id: string;
  category: "Courses" | "Virtual Internships" | "Certifications" | "Events" | "Tools";
  name: string;
  provider: string;
  duration: string;
  level?: string;
  skill: string;
  pathwayMatch: string[]; // pathway keywords this resource serves
  moroccoNote: string;
  link: string;
  popular?: boolean;
};

export const RESOURCES: Resource[] = [
  // Courses
  { id: "c1", category: "Courses", name: "Google Data Analytics", provider: "Coursera", duration: "6 months", level: "Beginner", skill: "Data analysis, SQL, R", pathwayMatch: ["data", "analyst", "analytics"], moroccoNote: "Highly valued at OCP, BMCE, and inwi for data roles.", link: "https://www.coursera.org/professional-certificates/google-data-analytics" },
  { id: "c2", category: "Courses", name: "Python for Everybody", provider: "Coursera", duration: "8 months", level: "Beginner", skill: "Python programming", pathwayMatch: ["data", "analyst", "tech"], moroccoNote: "Foundational skill for data jobs across Casablanca tech scene.", link: "https://www.coursera.org/specializations/python" },
  { id: "c3", category: "Courses", name: "Excel Skills for Business", provider: "Coursera", duration: "6 months", level: "Intermediate", skill: "Advanced Excel, modeling", pathwayMatch: ["data", "finance", "consulting", "analyst"], moroccoNote: "Required for analyst roles at Attijariwafa and BCG Casablanca.", link: "https://www.coursera.org/specializations/excel" },
  { id: "c4", category: "Courses", name: "Business Foundations", provider: "Wharton / Coursera", duration: "6 months", level: "Beginner", skill: "Business fundamentals", pathwayMatch: ["consulting", "finance", "management"], moroccoNote: "Strong signal for consulting interviews at McKinsey & BCG.", link: "https://www.coursera.org/specializations/wharton-business-foundations" },
  { id: "c5", category: "Courses", name: "Strategy Consulting", provider: "Copenhagen / Coursera", duration: "4 weeks", level: "Intermediate", skill: "Strategic frameworks", pathwayMatch: ["consulting", "strategy"], moroccoNote: "Frameworks used daily at Roland Berger Casablanca.", link: "https://www.coursera.org/learn/strategy-consulting" },
  { id: "c6", category: "Courses", name: "Financial Markets", provider: "Yale / Coursera", duration: "7 weeks", level: "Intermediate", skill: "Markets, valuation", pathwayMatch: ["finance", "banking"], moroccoNote: "Aligned with CDG Capital and Attijari Intermédiation roles.", link: "https://www.coursera.org/learn/financial-markets-global" },
  { id: "c7", category: "Courses", name: "Financial Accounting", provider: "Wharton / Coursera", duration: "4 weeks", level: "Beginner", skill: "Accounting fundamentals", pathwayMatch: ["finance", "audit"], moroccoNote: "Core for Big 4 audit roles in Morocco.", link: "https://www.coursera.org/learn/wharton-accounting" },
  { id: "c8", category: "Courses", name: "Bloomberg Market Concepts", provider: "Bloomberg", duration: "8 hours", level: "Beginner", skill: "Markets literacy", pathwayMatch: ["finance", "banking"], moroccoNote: "Free certification recognized by all banks in Morocco.", link: "https://portal.bloombergforeducation.com/courses/bmc" },
  { id: "c9", category: "Courses", name: "CFA Investment Foundations", provider: "CFA Institute", duration: "100 hours", level: "Beginner", skill: "Investment basics", pathwayMatch: ["finance", "investment"], moroccoNote: "Free credential — opens doors at CDG and Wafa Gestion.", link: "https://www.cfainstitute.org/programs/investment-foundations" },
  { id: "c10", category: "Courses", name: "Meta Front-End Developer", provider: "Coursera", duration: "7 months", level: "Beginner", skill: "React, JavaScript, HTML/CSS", pathwayMatch: ["tech", "developer", "frontend"], moroccoNote: "Direct path to dev roles at OCP Solutions, inwi, Capgemini.", link: "https://www.coursera.org/professional-certificates/meta-front-end-developer" },
  { id: "c11", category: "Courses", name: "Google UX Design", provider: "Coursera", duration: "6 months", level: "Beginner", skill: "UX research, design", pathwayMatch: ["tech", "design", "product"], moroccoNote: "Growing demand at Maroc Telecom and HPS for UX talent.", link: "https://www.coursera.org/professional-certificates/google-ux-design" },
  { id: "c12", category: "Courses", name: "AWS Cloud Practitioner", provider: "AWS", duration: "30 hours", level: "Beginner", skill: "Cloud fundamentals", pathwayMatch: ["tech", "cloud", "developer"], moroccoNote: "Free training — required for cloud roles at all Moroccan IT firms.", link: "https://aws.amazon.com/training/awsacademy/" },
  { id: "c13", category: "Courses", name: "Communication Skills", provider: "LinkedIn Learning", duration: "5 hours", level: "Beginner", skill: "Communication", pathwayMatch: ["all"], moroccoNote: "Soft skill universally valued in Moroccan corporate culture.", link: "https://www.linkedin.com/learning/topics/communication" },
  { id: "c14", category: "Courses", name: "Presentation Skills", provider: "Coursera", duration: "5 weeks", level: "Beginner", skill: "Presentation", pathwayMatch: ["all"], moroccoNote: "Critical for client-facing consulting and sales roles.", link: "https://www.coursera.org/learn/public-speaking" },
  { id: "c15", category: "Courses", name: "English for Business", provider: "Coursera", duration: "5 months", level: "Intermediate", skill: "Business English", pathwayMatch: ["all"], moroccoNote: "Differentiator in a French-dominant market — top firms require it.", link: "https://www.coursera.org/specializations/business-english" },
  // Virtual Internships (Forage)
  { id: "f1", category: "Virtual Internships", name: "Forward Program", provider: "McKinsey & Company", duration: "5-6 hours", skill: "Leadership, problem solving", pathwayMatch: ["consulting", "strategy"], moroccoNote: "Popular in Morocco — flagged on top CVs.", link: "https://www.theforage.com/simulations/mckinsey/forward-program-y6mr", popular: true },
  { id: "f2", category: "Virtual Internships", name: "Strategy Consulting", provider: "BCG", duration: "4-5 hours", skill: "Strategy, market sizing", pathwayMatch: ["consulting", "strategy"], moroccoNote: "Popular in Morocco — recognized by BCG Casablanca recruiters.", link: "https://www.theforage.com/simulations/bcg/strategy-consulting-9o8x", popular: true },
  { id: "f3", category: "Virtual Internships", name: "Audit & Assurance", provider: "KPMG", duration: "3-4 hours", skill: "Audit fundamentals", pathwayMatch: ["audit", "finance"], moroccoNote: "Popular in Morocco — KPMG Casablanca uses for screening.", link: "https://www.theforage.com/simulations/kpmg-us/audit-tnma", popular: true },
  { id: "f4", category: "Virtual Internships", name: "Technology Consulting", provider: "Deloitte", duration: "4-5 hours", skill: "Tech advisory", pathwayMatch: ["tech", "consulting"], moroccoNote: "Popular in Morocco — Deloitte hires from these completers.", link: "https://www.theforage.com/simulations/deloitte-au/technology-qa9o", popular: true },
  { id: "f5", category: "Virtual Internships", name: "Investment Banking", provider: "JP Morgan", duration: "5-6 hours", skill: "M&A, financial modeling", pathwayMatch: ["finance", "banking"], moroccoNote: "Strong CV signal for CFG Bank and Attijari Finances Corp.", link: "https://www.theforage.com/simulations/jpmorgan/investment-banking-w98p" },
  { id: "f6", category: "Virtual Internships", name: "Engineering Internship", provider: "Goldman Sachs", duration: "4 hours", skill: "Software engineering", pathwayMatch: ["tech", "finance"], moroccoNote: "Useful for fintech roles at HPS and Wafacash Digital.", link: "https://www.theforage.com/simulations/goldman-sachs/software-engineering-cn4r" },
  { id: "f7", category: "Virtual Internships", name: "Digital Intelligence", provider: "PwC", duration: "3-4 hours", skill: "Data, automation", pathwayMatch: ["data", "consulting"], moroccoNote: "Aligns with PwC Maroc digital transformation projects.", link: "https://www.theforage.com/simulations/pwc-us/digital-intelligence-jrwe" },
  { id: "f8", category: "Virtual Internships", name: "Data Analytics", provider: "Accenture", duration: "5-6 hours", skill: "Data analysis", pathwayMatch: ["data", "analyst"], moroccoNote: "Direct path to Accenture Maroc analyst hiring track.", link: "https://www.theforage.com/simulations/accenture-na/data-analytics-d2y8" },
  { id: "f9", category: "Virtual Internships", name: "Future Leaders Programme", provider: "Unilever", duration: "4-5 hours", skill: "Marketing, leadership", pathwayMatch: ["marketing", "management"], moroccoNote: "Strong fit for Unilever Maghreb graduate program.", link: "https://www.theforage.com/simulations/unilever/future-leaders-programme-66tx" },
  { id: "f10", category: "Virtual Internships", name: "Brandstorm Challenge", provider: "L'Oréal", duration: "6 hours", skill: "Brand strategy", pathwayMatch: ["marketing"], moroccoNote: "L'Oréal Maroc actively recruits Brandstorm participants.", link: "https://www.theforage.com/simulations/loreal" },
  { id: "f11", category: "Virtual Internships", name: "Management Trainee", provider: "Nestlé", duration: "4-5 hours", skill: "FMCG operations", pathwayMatch: ["management", "marketing"], moroccoNote: "Aligned with Nestlé Maghreb graduate intake.", link: "https://www.theforage.com/simulations/nestle" },
  { id: "f12", category: "Virtual Internships", name: "Digital Marketing", provider: "P&G", duration: "5 hours", skill: "Brand & digital marketing", pathwayMatch: ["marketing"], moroccoNote: "Useful for FMCG marketing roles in Casablanca.", link: "https://www.theforage.com/simulations/pwc-us/digital-marketing" },
];

export const RESOURCE_CATEGORIES = ["All", "Courses", "Virtual Internships", "Certifications", "Events", "Tools"] as const;
