// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const supabaseKey =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined);

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_ANON_KEY');
}

const SUPABASE_URL = supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = supabaseKey;
const REMEMBER_ME_KEY = 'cariva.rememberMe';

const authStorage: Storage = {
  getItem: (key: string) => {
    const localValue = localStorage.getItem(key);
    if (localValue !== null) return localValue;
    return sessionStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    const rememberMe = localStorage.getItem(REMEMBER_ME_KEY) !== 'false';
    if (rememberMe) {
      localStorage.setItem(key, value);
      sessionStorage.removeItem(key);
    } else {
      sessionStorage.setItem(key, value);
      localStorage.removeItem(key);
    }
  },
  removeItem: (key: string) => {
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  },
  clear: () => {},
  key: (index: number) => localStorage.key(index) ?? sessionStorage.key(index),
  get length() {
    return localStorage.length + sessionStorage.length;
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});